skfl/andersen-task

src/main/java/com/andersentask/bookshop/BookshopApplication.java
src/main/java/com/andersentask/bookshop/book/dtos/BookDTO.java
src/main/java/com/andersentask/bookshop/book/entities/Book.java
src/main/java/com/andersentask/bookshop/book/enums/BookStatus.java
src/main/java/com/andersentask/bookshop/book/exceptions/NoSuchBookException.java
src/main/java/com/andersentask/bookshop/book/mappers/BookMapper.java
src/main/java/com/andersentask/bookshop/book/repositories/BookRepository.java
src/main/java/com/andersentask/bookshop/book/services/implementations/BookServiceImpl.java
src/main/java/com/andersentask/bookshop/book/services/interfaces/BookService.java

Revert "Revert "Feature: Book entity and service implementation""

---

src/main/java/com/andersentask/bookshop/book/enums/BookStatus.java

Fix: "Book"

---

src/main/java/com/andersentask/bookshop/book/services/BookService.java

Description: add method to check book list if they are avaliable<3

Update: "book check book method"

---

src/main/java/com/andersentask/bookshop/request/entities/Request.java
src/main/java/com/andersentask/bookshop/request/enums/RequestStatus.java
src/main/java/com/andersentask/bookshop/request/services/RequestService.java

Description: Added getRequestsThatReadyToOrder() and moved RequestStatus to packed enums

Update: "Request"

---

pom.xml
src/main/resources/logback.xml

Add logback dependency and xml configuration

Feature: "Add logback"

---

src/main/java/com/andersentask/bookshop/order/entities/Order.java
src/main/java/com/andersentask/bookshop/order/enums/OrderStatus.java
src/main/java/com/andersentask/bookshop/order/facade/OrderFacade.java
src/main/java/com/andersentask/bookshop/order/repositories/OrderRepository.java
src/main/java/com/andersentask/bookshop/order/service/OrderService.java

Fix: "Order"

---

src/main/java/com/andersentask/bookshop/book/services/BookService.java
src/main/java/com/andersentask/bookshop/order/service/OrderService.java

-- add calculation of cost of List<Book>
-- add filter of List<Book> to available and out_of_stock books

update: "book"

---

src/main/java/com/andersentask/bookshop/book/enums/BookStatus.java
src/main/java/com/andersentask/bookshop/book/repositories/BookRepository.java
src/main/java/com/andersentask/bookshop/book/repositories/interfaces/BookCollectionRepository.java
src/main/java/com/andersentask/bookshop/book/services/BookService.java

close issue https://github.com/skfl/andersen-task/issues/10;
remove unnecessary interface ```BookCollectionRepository```

Fix: "Remove unnecessary method from BookStatus"

---

src/main/java/com/andersentask/bookshop/order/enums/OrderStatus.java
src/main/java/com/andersentask/bookshop/order/service/OrderService.java
src/main/java/com/andersentask/bookshop/request/enums/RequestStatus.java
src/main/java/com/andersentask/bookshop/request/services/RequestService.java

-- delete method getInfoAboutOrders
-- merge 2 methods, that were responsible for creation order from requests. New method name is saveOrdersFromListOfRequests

Fix: "order and request"

---

pom.xml
src/test/java/com/andersentask/bookshop/user/service/UserServiceTest.java

Description: updated user test

Fix: "User test"

---

pom.xml
src/main/java/com/andersentask/bookshop/console/Commands.java
src/main/java/com/andersentask/bookshop/console/ConsoleAppContextConfig.java
src/main/java/com/andersentask/bookshop/console/ConsoleAppController.java
src/main/java/com/andersentask/bookshop/console/UserCommunication.java
src/main/java/com/andersentask/bookshop/console/enums/ResultOfOperation.java
src/main/java/com/andersentask/bookshop/utils/serialization/RepositoryDeserializer.java
src/main/java/com/andersentask/bookshop/utils/serialization/RepositorySerializer.java

Add feature to save/load application state from ```*.json``` files

Feature: "Serialization/deserialization application state"

---

console.properties
src/main/java/com/andersentask/bookshop/console/UserCommunication.java

Description: added custom property

Feature: "Custom property"

---

src/main/java/com/andersentask/bookshop/book/enums/BookStatus.java

Description: minor fixes with BookStatus

Fix: "Book enum"

---

src/main/java/com/andersentask/bookshop/book/entities/Book.java
src/main/java/com/andersentask/bookshop/book/repositories/BookRepository.java
src/main/java/com/andersentask/bookshop/book/services/BookService.java
src/main/java/com/andersentask/bookshop/common/CollectionRepository.java
src/main/java/com/andersentask/bookshop/console/Commands.java
src/main/java/com/andersentask/bookshop/console/ConsoleAppContextConfig.java
src/main/java/com/andersentask/bookshop/console/ConsoleAppController.java
src/main/java/com/andersentask/bookshop/console/EntityFactory.java
src/main/java/com/andersentask/bookshop/console/enums/ResultOfOperation.java
src/main/java/com/andersentask/bookshop/order/entities/Order.java
src/main/java/com/andersentask/bookshop/order/repositories/OrderRepository.java
src/main/java/com/andersentask/bookshop/order/service/OrderService.java
src/main/java/com/andersentask/bookshop/request/entities/Request.java
src/main/java/com/andersentask/bookshop/request/enums/RequestStatus.java
src/main/java/com/andersentask/bookshop/request/services/RequestService.java
src/main/java/com/andersentask/bookshop/user/enums/Role.java
src/main/java/com/andersentask/bookshop/user/service/UserService.java
src/main/java/com/andersentask/bookshop/utils/serialization/RepositoryDeserializer.java

Description: I edited the code to make it appear as if it was written by one person.

Fix: "General Style"

---

src/main/java/com/andersentask/bookshop/book/entities/Book.java
src/main/java/com/andersentask/bookshop/console/Commands.java
src/main/java/com/andersentask/bookshop/console/ConsoleAppContextConfig.java
src/main/java/com/andersentask/bookshop/console/EntityFactory.java
src/main/java/com/andersentask/bookshop/console/UserCommunication.java
src/main/java/com/andersentask/bookshop/order/entities/Order.java
src/main/java/com/andersentask/bookshop/order/service/OrderService.java

Description: replaced Double with BigDecimal

Fix: "Order and Book from Double to BigDecimal"

---

src/main/java/com/andersentask/bookshop/book/enums/BookStatus.java
src/main/java/com/andersentask/bookshop/book/repositories/BookRepository.java
src/main/java/com/andersentask/bookshop/common/CollectionRepository.java
src/main/java/com/andersentask/bookshop/console/ConsoleAppContextConfig.java
src/main/java/com/andersentask/bookshop/order/repositories/OrderRepository.java
src/main/java/com/andersentask/bookshop/request/repository/RequestRepository.java
src/main/java/com/andersentask/bookshop/user/repository/UserRepository.java
src/test/java/com/andersentask/bookshop/user/repository/UserRepositoryTest.java

Fix: "Book status and repository"
Description: deleted method delete from CollectionRepository
from BookRepository, RequestRepository, UserRepository, OrderRepository

Fix: "Book status repository"

---

src/main/java/com/andersentask/bookshop/console/Commands.java
src/main/java/com/andersentask/bookshop/console/ConsoleAppContextConfig.java
src/main/java/com/andersentask/bookshop/console/DefaultMessages.java
src/main/java/com/andersentask/bookshop/console/UserCommunication.java

-- update java docs 
-- move serializer init from Commands to ConsoleAppContextConfig
-- update of getAllBooksFromOrder method in Commands (no need in return of optional of list)

Fix: "Commands and UserCommunication"

---

pom.xml

update pom.xml to remove unnecessary dependency

Update: "Remove unnecessary dependency"

---

src/main/java/com/andersentask/bookshop/book/repositories/BookRepository.java
src/main/java/com/andersentask/bookshop/book/services/BookService.java
src/main/java/com/andersentask/bookshop/console/Commands.java
src/main/java/com/andersentask/bookshop/order/repositories/OrderRepository.java
src/main/java/com/andersentask/bookshop/order/service/OrderService.java
src/main/java/com/andersentask/bookshop/request/repository/RequestRepository.java
src/main/java/com/andersentask/bookshop/request/services/RequestService.java
src/test/java/com/andersentask/bookshop/order/service/OrderServiceTest.java
src/test/java/com/andersentask/bookshop/request/services/RequestServiceTest.java

--sort and get methods moved to repositories
--enhancement of some methods in repositories and services

Fix: "Services and repositories"

---

src/main/java/com/andersentask/bookshop/console/Commands.java
src/main/java/com/andersentask/bookshop/console/enums/ResultOfOperation.java
src/main/java/com/andersentask/bookshop/request/services/RequestService.java
src/test/java/com/andersentask/bookshop/request/services/RequestServiceTest.java

-- Split big methods into small ones
-- Enhancement of some code

Enhancement: "Commands"

---

src/main/java/com/andersentask/bookshop/console/Commands.java
src/main/java/com/andersentask/bookshop/console/ConsoleAppContextConfig.java
src/main/java/com/andersentask/bookshop/http/servlets/JsonServlet.java
src/main/java/com/andersentask/bookshop/order/entities/Order.java
src/main/java/com/andersentask/bookshop/order/repositories/OrderBooksSQLCommands.java
src/main/java/com/andersentask/bookshop/order/repositories/OrderMapper.java
src/main/java/com/andersentask/bookshop/order/repositories/OrderRepository.java
src/main/java/com/andersentask/bookshop/order/repositories/OrderSQLCommands.java
src/main/java/com/andersentask/bookshop/order/service/OrderService.java
src/main/resources/db/changelog/changeset/create-order_books-table.yaml
src/main/resources/db/changelog/changeset/create-orders-table.yaml
src/main/resources/db/changelog/db.changelog-master.yaml

-- move to DB with JDBC of order entity
-- tests not updated yet
-- we have problem with JSON and TimeStamp

Feature: "Order to db jdbc"
